spring:
  profiles.active: dev
  artemis:
    #    host: localhost
    broker-url: tcp://localhost:61616
    user: artemis
    password: artemis
    embedded:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: dev
  data:
    rest:
      base-path: /data-api
  datasource:
    generate-unique-name: false
    name: tacocloud

security:
  user:
    name: buzz
    password: infinity

taco:
  orders:
    pageSize: 10
  discount:
    codes:
      abcdef: 10

logging:
  level:
    root: "trace"
    org.springframework.web: "trace"
    org.hibernate: "error"

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword

logging:
  level:
    tacos: WARN
