spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: Taco-Cloud
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#  data:
#    rest:
#      base-path: /data-api
  datasource:
    name: tacocloud
    generate-unique-name: false
    url: jdbc:postgresql://45.151.30.229:5432/tacocloud
    driver-class-name: org.postgresql.Driver
    username: test
    password: QWerty!@3456
#    url: jdbc:h2:mem:tacocloud
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true

management:
  endpoints:
    access:
      default: unrestricted
logging:
  level:
    org.springframework.security: trace
taco:
  orders:
    pageSize: 20

---

spring:
  config:
    activate:
      on-profile: prod
  thymeleaf:
    cache: true
logging:
  level:
    org.springframework.security: warn