spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: Taco-Cloud
  thymeleaf:
    cache: false
  datasource:
    generate-unique-name: false
    name: tacocloud
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
management:
  endpoints:
    access:
      default: unrestricted
logging:
  level:
#    org.springframework.security: trace
    org.hibernate.sql: trace
    org.hibernate.type.descriptor.sql: trace
taco:
  orders:
    pageSize: 20

---

spring:
  config:
    activate:
      on-profile: prod
  thymeleaf:
    cache: true
logging:
  level:
    org.springframework.security: warn